### ISSUE TITLE
Code is not valid C89/C99/C11

### ISSUE THREAD

**Issue by mfukar** [CCareaga/heap_allocator#4] opened 2017-09-18 09:28 UTC
Following the instructions in README.md leads to a segmentation fault. Steps to reproduce:

1. `git clone https://github.com/CCareaga/heap_allocator.git && git checkout b4058f452e8f8052f5813509634c58fd3753e80f`
2. `gcc main.c llist.c heap.c -o heap_test && ./heap_test`

```
$ gcc main.c llist.c heap.c -o heap_test && ./heap_test
heap.c:6:27: warning: cast to 'node_t *' (aka 'struct node_t *') from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-pointer-cast]
    node_t *init_region = (node_t *) start;
                          ^
heap.c:12:5: warning: implicit declaration of function 'add_node' is invalid in C99 [-Wimplicit-function-declaration]
    add_node(heap->bins[get_bin_index(init_region->size)], init_region);
    ^
heap.c:21:21: warning: implicit declaration of function 'get_best_fit' is invalid in C99 [-Wimplicit-function-declaration]
    node_t *found = get_best_fit(temp, size);
                    ^
heap.c:21:13: warning: incompatible integer to pointer conversion initializing 'node_t *' (aka 'struct node_t *') with an expression of type 'int' [-Wint-conversion]
    node_t *found = get_best_fit(temp, size);
            ^       ~~~~~~~~~~~~~~~~~~~~~~~~
heap.c:25:15: warning: incompatible integer to pointer conversion assigning to 'node_t *' (aka 'struct node_t *') from 'int' [-Wint-conversion]
        found = get_best_fit(temp, size);
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~
heap.c:29:17: warning: incompatible pointer types initializing 'node_t *' (aka 'struct node_t *') with an expression of type 'char *' [-Wincompatible-pointer-types]
        node_t *split = ((char *) found + sizeof(node_t) + sizeof(footer_t)) + size;
                ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
heap.c:44:5: warning: implicit declaration of function 'remove_node' is invalid in C99 [-Wimplicit-function-declaration]
    remove_node(heap->bins[index], found);
    ^
heap.c:67:14: warning: comparison between pointer and integer ('node_t *' (aka 'struct node_t *') and 'uint32_t' (aka 'unsigned int'))
    if (head == heap->start) {
        ~~~~ ^  ~~~~~~~~~~~
heap.c:74:20: warning: cast to 'node_t *' (aka 'struct node_t *') from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-pointer-cast]
    node_t *prev = (node_t *) * ((uint32_t *) ((char *) head - sizeof(footer_t)));
                   ^
heap.c:108:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
heap.c:135:41: warning: cast to 'char *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-pointer-cast]
    footer_t *wild_foot = (footer_t *) ((char *) heap->end - sizeof(footer_t));
                                        ^
11 warnings generated.
[1]    3559 segmentation fault  ./heap_test
```

**Comment by CCareaga** [comment] 2017-09-18 16:53
Most of these warnings have to do with the various casts I do from unsigned int to a pointer. On a 32-bit system, this is not a problem because there is no size difference. To fix these warnings and clear things up I have changed the ```uint32_t``` types to ```unsigned int``` and I have used ```uintptr_t``` to cast integers to pointers. I am not sure this gets rid of all warnings on your end but it seems to silence them for me. I am going to guess these warnings aren't what's causing your seg fault. To debug I usually step through with GDB therefore it may be difficult to determine what's causing it for you. I could maybe make a version that prints a bunch of statements out along the way so we could narrow down where the crash is at.

**Comment by dayang** [comment] 2017-09-19 04:10
I compile and run the program in windows and it crashs also, and I find the reason.
In main.c file when you malloc the memory of heap->bins[i], you didn't 
`memset(heap->bins[i], 0, sizeof(bin_t))`
 which cause `bin->head == NULL` is false in add_node function.
That causes `current->size` is unavailable which makes program crash.

**Comment by CCareaga** [comment] 2017-09-19 15:15
Good catch @dayang thank you for noticing this. I hope there aren't any other spots where I forget to memset, I guess I assumed the malloc'd memory would be empty. I will fix this.

**Comment by Spriithy** [comment] 2017-09-20 15:51
Compiling with `gcc -O3 *.c -o heap_test` yielded the same crash issue, but switching to `clang` in place of `gcc` turned out to go fine.

EDIT: Now I see the crash still holds after the `memset` fix on gcc only. Digging into it...

**Comment by CCareaga** [comment] 2017-09-20 16:09
@Spriithy interesting, is the crash happening before any output is printed? Works on both  gcc 4.4.7 and clang 3.4.2 for me.

**Comment by Spriithy** [comment] 2017-09-20 16:14
I am using gcc 6.3.0 and clang 4.0 on Ubuntu 17.04

**Comment by Spriithy** [comment] 2017-09-20 16:16
@CCareaga As for your initial question, the segmentation fault spawns right before any output is generated.

**Comment by CCareaga** [comment] 2017-09-20 16:30
@Spriithy That makes me think that it is not something that is off in the allocator but something is going wrong during the initialization of the heap. I didn't add a memset after the malloc for the heap structure since it gets written to in ```init_heap```. You could also make sure non of the malloc calls fail. Other than that the code would need to be stepped-through.

**Comment by jcstr** [comment] 2017-10-04 04:33
Hi, i'm getting segmentation fault, trying with both gcc, clang (latest versions), but at the end of building it get's the same issue.

I'm on a x86_64 system, just have the idea to make the proyect on c++, that's why i forked it.

Thanks a lot for sharing this!
Thanks in advance.
Cheers!

Edit: just delete silly question(s).

**Comment by CCareaga** [comment] 2017-10-04 15:19
@51v4n A few people have said they are getting seg-faults, but I can't reproduce this behavior on my system. In order to debug I would need to step through with a debugger or know which line is triggering the seg-fault. If you could provide some more information that would be helpful, in the mean time I will try to figure out some possible places it could be happening.

**Comment by CCareaga** [comment] 2017-10-05 04:20
@51v4n I may have fixed the problem, it looks like there were some discrepancies between 32 and 64-bit code. Some pointers were being truncated to 4 bytes rather than 8... Let me know if it still seg faults.

**Comment by jcstr** [comment] 2017-10-05 05:18
@CCareaga Looks reasonable, didn't realize that, thanks for let me know, i'll do the necessary changes, i'll give you feedback when it's done.

**Comment by CCareaga** [comment] 2017-10-05 21:00
@51v4n I have updated the repo it should work, I should probably clean things up and make sure it is consistent. I am going to close this issue though because I believe the seg-fault problem is resolved.

**Closed as completed by CCareaga** 2017-10-05 21:00 UTC
